[package]
name = "cv-viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
cv-core = { path = "../core" }
egui = "0.33.3"
eframe = { version = "0.33.3", features = ["wgpu"] }
bytemuck = "1.21.0"
glam = "0.29.3"

[features]
default = []
