[package]
name = "cv-optimize"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { workspace = true }
cv-core = { path = "../core" }
cv-hal = { path = "../hal" }
thiserror = { workspace = true }
faer = "0.24.0"
